# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mahasiswa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import mysql.connector as mc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 395)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 160, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 10, 211, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 381, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 200, 381, 151))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 170, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 360, 381, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_2.addWidget(self.lineEdit_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        
        self.pushButton.clicked.connect(self.Insertmahasiswa)
        self.pushButton_2.clicked.connect(self.updatemahasiswa)
        self.pushButton_3.clicked.connect(self.deletemahasiswa)
        self.pushButton_4.clicked.connect(self.loadmahasiswa)
        self.pushButton_5.clicked.connect(self.filtermahasiswa)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
    def getBynpm(self,row):
        try:
            npmitem = self.tableWidget.item(row,0)
            namaitem = self.tableWidget.item(row,1)
            kelasitem = self.tableWidget.item(row,2)
            jurusanitem = self.tableWidget.item(row,3)
            tanggal_lahiritem = self.tableWidget.item(row,4)
            if npmitem :
                valueid = npmitem.text()
                valuename = namaitem.text()
                valuekelas = kelasitem.text()
                valuejurusan = jurusanitem.text()
                valuetanggal_lahir = tanggal_lahiritem.text()
                self.lineEdit.setText(valueid)
                self.lineEdit_2.setText(valuename)
                self.lineEdit_3.setText(valuekelas)
                self.lineEdit_4.setText(valuejurusan)
                self.lineEdit_5.setText(valuetanggal_lahir)
            self.label_3.setText("Data Mahasiswa Berhasil Dipillih")
        except mc.Error as err:
            self.label_3.setText("Data Mahasiswa Gagal Dipilih")
            
    def Insertmahasiswa(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="dtb_kampus"
        )   
            cursor = mydb.cursor()
            npm = self.lineEdit.text()
            nama = self.lineEdit_2.text()
            kelas = self.lineEdit_3.text()
            jurusan = self.lineEdit_4.text()
            tanggal_lahir = self.lineEdit_5.text()
            sql ="INSERT INTO mahasiswa (npm,nama,kelas,jurusan,tanggal_lahir) VALUES (%s,%s,%s,%s,%s)"
            val = (npm,nama,kelas,jurusan,tanggal_lahir)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_6.setText("Data Mahasiswa Berhasil Disimpan")
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
        except mc.Error as err:
            self.label_6.setText("Data Mahasiswa Gagal Disimpan")
            
    def updatemahasiswa(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="dtb_kampus"
        )   
            cursor = mydb.cursor()
            npm = self.lineEdit.text()
            nama = self.lineEdit_2.text()
            kelas = self.lineEdit_3.text()
            jurusan = self.lineEdit_4.text()
            tanggal_lahir = self.lineEdit_5.text()
            sql ="UPDATE mahasiswa Set nama = (%s), kelas = (%s), jurusan = (%s), tanggal_lahir = (%s)  WHERE id = (%s)"
            val = (nama,kelas,jurusan,tanggal_lahir,npm)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_6.setText("Data Mahasiswa Berhasil DiUpdate")
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
        except mc.Error as err:
            self.label_6.setText("Data Mahasiswa Gagal DiUpdate")
            
    def deletemahasiswa(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="dtb_kampus"
        )
            cursor = mydb.cursor()
            npm = self.lineEdit.text()
            sql ="DELETE FROM mahasiswa WHERE npm = %s"
            val = (npm,)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_6.setText("Data Mahasiswa Berhasil DiDelete")
            self.lineEdit.setText("")
            self.lineEdit_2.setText("")
            self.lineEdit_3.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_5.setText("")
        except mc.Error as err:
            self.label_6.setText("Data Mahasiswa Gagal DiDelete") 
            
    def loadmahasiswa(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="dtb_kampus"
        )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM mahasiswa ORDER BY npm ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
            self.label_6.setText("Data Mahasiswa Berhasil DiTampilkan")
        except mc.Error as err:
            self.label_6.setText("Data Mahasiswa Gagal DiTampilkan")
            
    def filtermahasiswa(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="dtb_kampus"
        )
            mycursor = mydb.cursor()
            srckat = self.lineEdit_6.text()
            sql = "SELECT * FROM mahasiswa WHERE npm LIKE %s OR nama LIKE %s ORDER BY npm ASC"
            val = (f"%{srckat}%", f"%{srckat}%")
            mycursor.execute(sql,val)
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
            self.label_6.setText("Hasil Filter Data Kategori ")
        except mc.Error as err:
            self.label_6.setText("Filter Gagal")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "NPM"))
        self.label_2.setText(_translate("Form", "NAMA"))
        self.label_3.setText(_translate("Form", "KELAS"))
        self.label_4.setText(_translate("Form", "JURUSAN"))
        self.label_5.setText(_translate("Form", "TANGGAL LAHIR"))
        self.pushButton.setText(_translate("Form", "INSERT"))
        self.pushButton_2.setText(_translate("Form", "UPDATE"))
        self.pushButton_3.setText(_translate("Form", "DELETE"))
        self.pushButton_4.setText(_translate("Form", "LOAD DATA"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NPM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "NAMA"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "KELAS"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "JURUSAN"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "TANGGAL LAHIR"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.pushButton_5.setText(_translate("Form", "FILTER DATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
